;; p99-patcher - A patcher/launcher for the project1999.org Everquest server
;; Copyright (C) 2013 Matthew Carter
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; map.lisp

(in-package #:p99-patcher)

;;; "p99-patcher" goes here. Hacks and glory await!

(defparameter *zone-name-map*
  (list
   "South Qeynos" "qeynos"
   "North Qeynos" "qeynos2"
   "The Surefall Glade" "qrg"
   "The Qeynos Hills" "qeytoqrg"
   "Highpass Hold" "highpass"
   "High Keep" "highkeep"
   "North Freeport" "freportn"
   "West Freeport" "freportw"
   "East Freeport" "freporte"
   "The Liberated Citadel of Runnyeye" "runnyeye"
   "Liberated Citadel of Runnyeye" "runnyeye"
   "The Western Plains of Karana" "qey2hh1"
   "Western Plains of Karana" "qey2hh1"
   "The Northern Plains of Karana" "northkarana"
   "Northern Plains of Karana" "northkarana"
   "The Southern Plains of Karana" "southkarana"
   "Southern Plains of Karana" "southkarana"
   "Eastern Plains of Karana" "eastkarana"
   "Gorge of King Xorbb" "beholder"
   "Blackburrow" "blackburrow"
   "The Lair of the Splitpaw" "paw"
   "Infected Paw" "paw"
   "Rivervale" "rivervale"
   "Kithicor Forest" "kithicor"
   "West Commonlands" "commons"
   "East Commonlands" "ecommons"
   "The Erudin Palace" "erudnint"
   "Erudin" "erudnext"
   "The Nektulos Forest" "nektulos"
   "The Nektulos Forest" "nektulos"
   "Sunset Home" "cshome"
   "The Lavastorm Mountains" "lavastorm"
   "Lavastorm Mountains" "lavastorm"
   "Nektropos" "nektropos"
   "Halas" "halas"
   "Everfrost Peaks" "everfrost"
   "Solusek's Eye" "soldunga"
   "Nagafen's Lair" "soldungb"
   "Misty Thicket" "misty"
   "Northern Desert of Ro" "nro"
   "Southern Desert of Ro" "sro"
   "Befallen" "befallen"
   "Oasis of Marr" "oasis"
   "Toxxulia Forest" "tox"
   "The Hole" "hole"
   "Neriak - Foreign Quarter" "neriaka"
   "Neriak Foreign Quarter" "neriaka"
   "Neriak - Commons" "neriakb"
   "Neriak Commons" "neriakb"
   "Neriak - 3rd Gate" "neriakc"
   "Neriak Palace" "neriakd"
   "Najena" "najena"
   "The Qeynos Aqueduct System" "qcat"
   "Innothule Swamp" "innothule"
   "The Feerrott" "feerrott"
   "Accursed Temple of CazicThule" "cazicthule"
   "Oggok" "oggok"
   "The Rathe Mountains" "rathemtn"
   "Rathe Mountains" "rathemtn"
   "Lake Rathetear" "lakerathe"
   "Grobb" "grobb"
   "Aviak Village" "aviak"
   "The Greater Faydark" "gfaydark"
   "Greater Faydark" "gfaydark"
   "Ak'Anon" "akanon"
   "Steamfont Mountains" "steamfont"
   "The Lesser Faydark" "lfaydark"
   "Lesser Faydark" "lfaydark"
   "Crushbone" "crushbone"
   "The Castle of Mistmoore" "mistmoore"
   "South Kaladim" "kaladima"
   "Northern Felwithe" "felwithea"
   "Southern Felwithe" "felwitheb"
   "The Estate of Unrest" "unrest"
   "Kedge Keep" "kedge"
   "The City of Guk" "guktop"
   "The Ruins of Old Guk" "gukbottom"
   "North Kaladim" "kaladimb"
   "Butcherblock Mountains" "butcher"
   "Ocean of Tears" "oot"
   "Dagnor's Cauldron" "cauldron"
   "The Plane of Sky" "airplane"
   "The Plane of Fear" "fearplane"
   "The Permafrost Caverns" "permafrost"
   "Kerra Isle" "kerraridge"
   "Paineel" "paineel"
   "Plane of Hate" "hateplane"
   "The Arena" "arena"
   "Field of Bone" "fieldofbone"
   "The Warsliks Woods" "warslikswood"
   "The Temple of Solusek Ro" "soltemple"
   "The Temple of Droga" "droga"
   "Cabilis West" "cabwest"
   "The Swamp of No Hope" "swampofnohope"
   "Firiona Vie" "firiona"
   "Lake of Ill Omen" "lakeofillomen"
   "The Dreadlands" "dreadlands"
   "The Burning Wood" "burningwood"
   "Kaesora" "kaesora"
   "The Ruins of Sebilis" "sebilis"
   "The City of Mist" "citymist"
   "The Skyfire Mountains" "skyfire"
   "Frontier Mountains" "frontiermtns"
   "The Overthere" "overthere"
   "The Emerald Jungle" "emeraldjungle"
   "Trakanon's Teeth" "trakanon"
   "Timorous Deep" "timorous"
   "Kurn's Tower" "kurn"
   "Erud's Crossing" "erudsxing"
   "The Stonebrunt Mountains" "stonebrunt"
   "The Warrens" "warrens"
   "Karnor's Castle" "karnor"
   "Chardok" "chardok"
   "The Crypt of Dalnir" "dalnir"
   "The Howling Stones" "charasis"
   "Cabilis East" "cabeast"
   "The Mines of Nurga" "nurga"
   "Veeshan's Peak" "veeshan"
   "Veksar" "veksar"
   "The Iceclad Ocean" "iceclad"
   "The Tower of Frozen Shadow" "frozenshadow"
   "Velketor's Labyrinth" "velketor"
   "Kael Drakkel" "kael"
   "Skyshrine" "skyshrine"
   "Skyshrine" "skyshrine"
   "The City of Thurgadin" "thurgadina"
   "Eastern Wastes" "eastwastes"
   "Cobaltscar" "cobaltscar"
   "The Great Divide" "greatdivide"
   "The Wakening Land" "wakening"
   "The Western Wastes" "westwastes"
   "The Crystal Caverns" "crystal"
   "Dragon Necropolis" "necropolis"
   "The Temple of Veeshan" "templeveeshan"
   "Siren's Grotto" "sirens"
   "The Plane of Mischief" "mischiefplane"
   "The Plane of Growth" "growthplane"
   "The Sleeper's Tomb" "sleeper"
   "Icewell Keep" "thurgadinb"
   "Marauders Mire" "erudsxing2"
   "Shadow Haven" "shadowhaven"
   "The Bazaar" "bazaar"
   "The Bazaar" "bazaar"
   "Nexus" "nexus"
   "The Echo Caverns" "echo"
   "The Acrylia Caverns" "acrylia"
   "The City of Shar Vahl" "sharvahl"
   "The Paludal Caverns" "paludal"
   "The Fungus Grove" "fungusgrove"
   "Vex Thal" "vexthal"
   "Sanctus Seru" "sseru"
   "Katta Castellum" "katta"
   "Netherbian Lair" "netherbian"
   "Ssraeshza Temple" "ssratemple"
   "Grieg's End" "griegsend"
   "The Deep" "thedeep"
   "Shadeweaver's Thicket" "shadeweaver"
   "Hollowshade Moor" "hollowshade"
   "Grimling Forest" "grimling"
   "Marus Seru" "mseru"
   "Mons Letalis" "letalis"
   "The Twilight Sea" "twilight"
   "The Grey" "thegrey"
   "The Tenebrous Mountains" "tenebrous"
   "The Maiden's Eye" "maiden"
   "The Dawnshroud Peaks" "dawnshroud"
   "The Scarlet Desert" "scarlet"
   "The Umbral Plains" "umbral"
   "The Akheva Ruins" "akheva"
   "The Arena Two" "arena2"
   "The Jaggedpine Forest" "jaggedpine"
   "Nedaria's Landing" "nedaria"
   "EverQuest Tutorial" "tutorial"
   "Loading Zone" "load"
   "New Loading Zone" "load2"
   "The Plane of Hate" "hateplaneb"
   "Shadowrest" "shadowrest"
   "The Mines of Gloomingdeep" "tutoriala"
   "The Mines of Gloomingdeep" "tutorialb"
   "Loading" "clz"
   "The Crypt of Decay" "codecay"
   "The Plane of Justice" "pojustice"
   "The Plane of Knowledge" "poknowledge"
   "The Plane of Tranquility" "potranquility"
   "The Plane of Nightmares" "ponightmare"
   "The Plane of Disease" "podisease"
   "The Plane of Innovation" "poinnovation"
   "Torment, the Plane of Pain" "potorment"
   "The Plane of Valor" "povalor"
   "Bastion of Thunder" "bothunder"
   "The Plane of Storms" "postorms"
   "The Halls of Honor" "hohonora"
   "The Tower of Solusek Ro" "solrotower"
   "Plane of War" "powar"
   "Drunder, the Fortress of Zek" "potactics"
   "The Plane of Air" "poair"
   "The Plane of Water" "powater"
   "The Plane of Fire" "pofire"
   "The Plane of Earth" "poeartha"
   "The Plane of Time A" "potimea"
   "The Temple of Marr" "hohonorb"
   "The Lair of Terris Thule" "nightmareb"
   "The Plane of Earth" "poearthb"
   "The Plane of Time B" "potimeb"
   "The Gulf of Gunthak" "gunthak"
   "Dulak's Harbor" "dulak"
   "The Torgiran Mines" "torgiran"
   "The Crypt of Nadox" "nadox"
   "Hate's Fury" "hatesfury"
   "Deepest Guk: Cauldron of Lost Souls" "guka"
   "The Rujarkian Hills: Bloodied Quarries" "ruja"
   "Takish-Hiz: Sunken Library" "taka"
   "Miragul's Menagerie: Silent Gallery" "mira"
   "Mistmoore's Catacombs: Forlorn Caverns" "mmca"
   "The Drowning Crypt" "gukb"
   "The Rujarkian Hills: Halls of War" "rujb"
   "Takish-Hiz: Shifting Tower" "takb"
   "Miragul's Menagerie: Frozen Nightmare" "mirb"
   "Mistmoore's Catacombs: Dreary Grotto" "mmcb"
   "Deepest Guk: Ancient Aqueducts" "gukc"
   "The Rujarkian Hills: Wind Bridges" "rujc"
   "Takish-Hiz: Fading Temple" "takc"
   "The Spider Den" "mirc"
   "Mistmoore's Catacombs: Struggles within the Progeny" "mmcc"
   "The Mushroom Grove" "gukd"
   "The Rujarkian Hills: Prison Break" "rujd"
   "Takish-Hiz: Royal Observatory" "takd"
   "Miragul's Menagerie: Hushed Banquet" "mird"
   "Mistmoore's Catacombs: Chambers of Eternal Affliction" "mmcd"
   "Deepest Guk: The Curse Reborn" "guke"
   "The Rujarkian Hills: Drudge Hollows" "ruje"
   "Takish-Hiz: River of Recollection" "take"
   "The Frosted Halls" "mire"
   "Mistmoore's Catacombs: Sepulcher of the Damned" "mmce"
   "Deepest Guk: Chapel of the Witnesses" "gukf"
   "The Rujarkian Hills: Fortified Lair of the Taskmasters" "rujf"
   "Takish-Hiz: Sandfall Corridors" "takf"
   "The Forgotten Wastes" "mirf"
   "Mistmoore's Catacombs: Scion Lair of Fury" "mmcf"
   "The Root Garden" "gukg"
   "The Rujarkian Hills: Hidden Vale of Deceit" "rujg"
   "Takish-Hiz: Balancing Chamber" "takg"
   "Miragul's Menagerie: Heart of the Menagerie" "mirg"
   "Mistmoore's Catacombs: Cesspits of Putrescence" "mmcg"
   "Deepest Guk: Accursed Sanctuary" "gukh"
   "The Rujarkian Hills: Blazing Forge" "rujh"
   "Takish-Hiz: Sweeping Tides" "takh"
   "The Morbid Laboratory" "mirh"
   "Mistmoore's Catacombs: Aisles of Blood" "mmch"
   "The Rujarkian Hills: Arena of Chance" "ruji"
   "Takish-Hiz: Antiquated Palace" "taki"
   "The Theater of Imprisoned Horror" "miri"
   "Mistmoore's Catacombs: Halls of Sanguinary Rites" "mmci"
   "The Rujarkian Hills: Barracks of War" "rujj"
   "Takish-Hiz: Prismatic Corridors" "takj"
   "Miragul's Menagerie: Grand Library" "mirj"
   "Mistmoore's Catacombs: Infernal Sanctuary" "mmcj"
   "Chardok: The Halls of Betrayal" "chardokb"
   "The Caverns of Exile" "soldungc"
   "The Abysmal Sea" "abysmal"
   "Natimbi, the Broken Shores" "natimbi"
   "Qinimi, Court of Nihilia" "qinimi"
   "Riwwi, Coliseum of Games" "riwwi"
   "Barindu, Hanging Gardens" "barindu"
   "Ferubi, Forgotten Temple of Taelosia" "ferubi"
   "Sewers of Nihilia, Pool of Sludg" "snpool"
   "Sewers of Nihilia, Lair of Trapp" "snlair"
   "Sewers of Nihilia, Purifying Pla" "snplant"
   "Sewers of Nihilia, Emanating Cre" "sncrematory"
   "Tipt, Treacherous Crags" "tipt"
   "Vxed, the Crumbling Caverns" "vxed"
   "Yxtta, Pulpit of Exiles" "yxtta"
   "Uqua, the Ocean God Chantry" "uqua"
   "Kod'Taz, Broken Trial Grounds" "kodtaz"
   "Ikkinz, Chambers of Transcendence" "ikkinz"
   "Qvic, Prayer Grounds of Calling" "qvic"
   "Inktu'Ta, the Unmasked Chapel" "inktuta"
   "Txevu, Lair of the Elite" "txevu"
   "Tacvi, The Broken Temple" "tacvi"
   "Qvic, the Hidden Vault" "qvicb"
   "Wall of Slaughter" "wallofslaughter"
   "The Bloodfields" "bloodfields"
   "Dranik's Scar" "draniksscar"
   "Nobles' Causeway" "causeway"
   "Muramite Proving Grounds A" "chambersa"
   "Muramite Proving Grounds B" "chambersb"
   "Muramite Proving Grounds C" "chambersc"
   "Muramite Proving Grounds D" "chambersd"
   "Muramite Proving Grounds E" "chamberse"
   "Muramite Proving Grounds F" "chambersf"
   "Muramite Proving Grounds G" "provinggrounds"
   "Anguish, the Fallen Palace" "anguish"
   "Dranik's Hollows A" "dranikhollowsa"
   "Dranik's Hollows B" "dranikhollowsb"
   "Dranik's Hollows C" "dranikhollowsc"
   "Catacombs of Dranik A" "dranikcatacombsa"
   "Catacombs of Dranik B" "dranikcatacombsb"
   "Catacombs of Dranik C" "dranikcatacombsc"
   "Sewers of Dranik A" "draniksewersa"
   "Sewers of Dranik B" "draniksewersb"
   "Sewers of Dranik C" "draniksewersc"
   "Riftseekers' Sanctum" "riftseekers"
   "Harbinger's Spire" "harbingers"
   "The Ruined City of Dranik" "dranik"
   "The Broodlands" "broodlands"
   "Stillmoon Temple" "stillmoona"
   "The Ascent" "stillmoonb"
   "Thundercrest Isles" "thundercrest"
   "Lavaspinner's Lair" "delvea"
   "Tirranun's Delve" "delveb"
   "The Nest" "thenest"
   "Guild Lobby" "guildlobby"
   "Guild Hall" "guildhall"
   "The Barter Hall" "barter"
   "Ruins of Illsalin" "illsalin"
   "Illsalin Marketplace" "illsalina"
   "Temple of Korlach" "illsalinb"
   "The Nargil Pits" "illsalinc"
   "Dreadspire Keep" "dreadspire"
   "The Hive" "drachnidhive"
   "The Hatchery" "drachnidhivea"
   "The Cocoons" "drachnidhiveb"
   "Queen Sendaii`s Lair" "drachnidhivec"
   "Stoneroot Falls" "westkorlach"
   "Prince's Manor" "westkorlacha"
   "Caverns of the Lost" "westkorlachb"
   "Lair of the Korlach" "westkorlachc"
   "The Undershore" "eastkorlach"
   "Snarlstone Dens" "eastkorlacha"
   "Shadow Spine" "shadowspine"
   "Corathus Creep" "corathus"
   "Sporali Caverns" "corathusa"
   "The Corathus Mines" "corathusb"
   "Shadowed Grove" "nektulosa"
   "Arcstone, Isle of Spirits" "arcstone"
   "Relic, the Artifact City" "relic"
   "Skylance" "skylance"
   "The Devastation" "devastation"
   "The Seething Wall" "devastationa"
   "Sverag, Stronghold of Rage" "rage"
   "Razorthorn, Tower of Sullon Zek" "ragea"
   "Ruins of Takish-Hiz" "takishruins"
   "The Root of Ro" "takishruinsa"
   "The Elddar Forest" "elddar"
   "Tunare's Shrine" "elddara"
   "Theater of Blood" "theater"
   "Deathknell, Tower of Dissonance" "theatera"
   "East Freeport" "freeporteast"
   "West Freeport" "freeportwest"
   "Freeport Sewers" "freeportsewers"
   "Academy of Arcane Sciences" "freeportacademy"
   "Temple of Marr" "freeporttemple"
   "Freeport Militia House: My Precious" "freeportmilitia"
   "Arena" "freeportarena"
   "City Hall" "freeportcityhall"
   "Theater of the Tranquil" "freeporttheater"
   "Hall of Truth: Bounty" "freeporthall"
   "North Desert of Ro" "northro"
   "South Desert of Ro" "southro"
   "Crescent Reach" "crescent"
   "Blightfire Moors" "moors"
   "Stone Hive" "stonehive"
   "Goru`kar Mesa" "mesa"
   "Blackfeather Roost" "roost"
   "The Steppes" "steppes"
   "Icefall Glacier" "icefall"
   "Valdeholm" "valdeholm"
   "Frostcrypt, Throne of the Shade King" "frostcrypt"
   "Sunderock Springs" "sunderock"
   "Vergalid Mines" "vergalid"
   "Direwind Cliffs" "direwind"
   "Ashengate, Reliquary of the Scale" "ashengate"
   "Highpass Hold" "highpasshold"
   "The Commonlands" "commonlands"
   "The Ocean of Tears" "oceanoftears"
   "Kithicor Forest" "kithforest"
   "Kithicor Woods" "kithicor"
   "Befallen" "befallenb"
   "HighKeep" "highpasskeep"
   "The Innothule Swamp" "innothuleb"
   "The Misty Thicket" "mistythicket"
   "Katta Castrum" "kattacastrum"
   "Thalassius, the Coral Keep" "thalassius"
   "Jewel of Atiiki" "atiiki"
   "Zhisza, the Shissar Sanctuary" "zhisza"
   "Silyssar, New Chelsith" "silyssar"
   "Solteris, the Throne of Ro" "solteris"
   "Barren Coast" "barren"
   "The Buried Sea" "buriedsea"
   "Jardel's Hook" "jardelshook"
   "Monkey Rock" "monkeyrock"
   "Suncrest Isle" "suncrest"
   "Deadbone Reef" "deadbone"
   "Blacksail Folly" "blacksail"
   "Maiden's Grave" "maidensgrave"
   "Redfeather Isle" "redfeather"
   "The Open Sea" "shipmvp"
   "The Open Sea" "shipmvu"
   "The Open Sea" "shippvu"
   "The Open Sea" "shipuvu"
   "The Open Sea" "shipmvm"
   "Fortress Mechanotus" "mechanotus"
   "Meldrath's Majestic Mansion" "mansion"
   "The Steam Factory" "steamfactory"
   "S.H.I.P. Workshop" "shipworkshop"
   "Gyrospire Beza" "gyrospireb"
   "Gyrospire Zeka" "gyrospirez"
   "Dragonscale Hills" "dragonscale"
   "Loping Plains" "lopingplains"
   "Hills of Shade" "hillsofshade"
   "Bloodmoon Keep" "bloodmoon"
   "Crystallos, Lair of the Awakened" "crystallos"
   "The Mechamatic Guardian" "guardian"
   "The Steamfont Mountains" "steamfontmts"
   "Crypt of Shade" "cryptofshade"
   "Deepscar's Den" "dragonscaleb"
   "Field of Scale" "oldfieldofbone"
   "Kaesora Library" "oldkaesoraa"
   "Kaesora Hatchery" "oldkaesorab"
   "Kurn's Tower" "oldkurn"
   "Bloody Kithicor" "oldkithicor"
   "Old Commonlands" "oldcommons"
   "Highpass Hold" "oldhighpass"
   "The Void A" "thevoida"
   "The Void B" "thevoidb"
   "The Void C" "thevoidc"
   "The Void D" "thevoidd"
   "The Void E" "thevoide"
   "The Void F" "thevoidf"
   "The Void G" "thevoidg"
   "Oceangreen Hills" "oceangreenhills"
   "Oceangreen Village" "oceangreenvillage"
   "BlackBurrow" "oldblackburrow"
   "Temple of Bertoxxulous" "bertoxtemple"
   "Korafax, Home of the Riders" "discord"
   "Citadel of the Worldslayer" "discordtower"
   "Old Bloodfields" "oldbloodfield"
   "The Precipice of War" "precipiceofwar"
   "City of Dranik" "olddranik"
   "Toskirakk" "toskirakk"
   "Korascian Warrens" "korascian"
   "Rathe Council Chamber" "rathechamber"
   "Brell's Rest" "brellsrest"
   "Fungal Forest" "fungalforest"
   "The Underquarry" "underquarry"
   "The Cooling Chamber" "coolingchamber"
   "Kernagir, the Shining City" "shiningcity"
   "Arthicrex" "arthicrex"
   "The Foundation" "foundation"
   "Lichen Creep" "lichencreep"
   "Pellucid Grotto" "pellucid"
   "Volska's Husk" "stonesnake"
   "Brell's Temple" "brellstemple"
   "The Convorteum" "convorteum"
   "Brell's Arena" "brellsarena"
   "Wedding Chapel" "weddingchapel"
   "Wedding Chapel" "weddingchapeldark"
   "Lair of the Risen" "dragoncrypt"
   "House of Thule" "thulehouse1"
   "House of Thule, Upper Floors" "thulehouse2"
   "The Grounds" "housegarden"
   "The Library" "thulelibrary"
   "The Well" "well"
   "Erudin Burning" "fallen"
   "Morell's Castle" "morellcastle"
   "Sanctum Somnium" "somnium"
   "Al'Kabor's Nightmare" "alkabormare"
   "Miragul's Nightmare" "miragulmare"
   "Fear Itself" "thuledream"
   "Sunrise Hills" "neighborhood"
   "Argath, Bastion of Illdaera" "argath"
   "Valley of Lunanyn" "arelis"
   "Sarith, City of Tides" "sarithcity"
   "Rubak Oseka, Temple of the Sea" "rubak"
   "Beasts' Domain" "beastdomain"
   "The Resplendent Temple" "resplendent"
   "Pillars of Alra" "pillarsalra"
   "Windsong Sanctuary" "windsong"
   "Erillion, City of Bronze" "cityofbronze"
   "Sepulcher of Order" "sepulcher"
   "Sepulcher East" "eastsepulcher"
   "Sepulcher West" "westsepulcher"
   "Shard's Landing" "shardslanding"
   "Valley of King Xorbb" "xorbb"
   "Kael Drakkel: The King's Madness" "kaelshard"
   "East Wastes: Zeixshi-Kar's Awakening" "eastwastesshard"
   "The Crystal Caverns: Fragment of Fear" "crystalshard"
   "The Breeding Grounds" "breedinggrounds"
   "Evantil, the Vile Oak" "eviltree"
   "Grelleth's Palace, the Chateau of Filth" "grelleth"
   "Chapterhouse of the Fallen" "chapterhouse"
   "Art Testing Domain" "arttest"
   "The Forgotten Halls" "fhalls"
   "Designer Apprentice" "apprentice"
   ))
